feat: Updating some dependencies
ExpediaGroup/steerage pull request #59
Opened 2023-02-03 21:28 UTC by YosafatEG

# Updating some dependencies

Bump eslint from 7.32.0 to 8.33.0
Bump commitizen from 4.2.6 to 4.3.0
Bump @vrbo/determination from 6.1.2 to 6.1.3
Bump tape from 5.6.1 to 5.6.3
Bump @hapi/topo from 5.1.0 to 6.0.0
Bump @hapi/hoek from 9.3.0 to 11.0.2

2023-02-07 20:41 UTC, shellbj requested changes

2023-02-07 20:41 UTC, shellbj commented on package.json
> +    "@vrbo/determination": "^6.1.3",
this range doesn't need to move

2023-02-07 20:41 UTC, shellbj commented on package.json
> +    "eslint": "^8.33.0",
`@hapi/eslint-config-hapi` and ``@hapi/eslint-plugin-hapi`  are deprecated and moved to `@hapi/eslint-plugin`; this should be part of this update for `eslint`

2023-02-07 20:41 UTC, shellbj commented on package.json
> +    "@hapi/topo": "^6.0.0",
Upgrading both of these will cause conflicts in other packages that consume this one.  

Minimally, they should be the lowest, newest, version possible (`^11.0.0` vs. `^11.0.2`); but I'm tempted to say we should use a range expansion (`^9.0.4 || ^10.0.0 || ^11.0.0`) on these until `hapi` upgrades can be rolled out across the product line.

2023-02-08 20:00 UTC, kisaiev commented on package.json
> +    "@hapi/hoek": "^9.0.4 || ^10.0.0 || ^11.0.0",
`@hapi/hoek` at [v11.0.0](https://www.npmjs.com/package/@hapi/hoek/v/11.0.0) is deprecated, so it's better to start with `^11.0.1` in v11 range.

2023-02-09 15:37 UTC, shellbj commented on .github/dependabot.yml
> +        update-types: ["version-update:semver-major"]
Include `hapi` here

2023-02-09 19:57 UTC, shellbj approved these changes

2023-02-09 21:08 UTC, kisaiev approved these changes

2023-02-09 21:24 UTC, merged